### ISSUE TITLE
[Error] Unable to Update My Address

### ISSUE THREAD

**Issue by rtcms** [E-Angadi/AngadiWeb#7]
Test URL - https://eangadi-a2aa8.web.app/account
When trying to update my Address I get the following error on console 

![Error](https://user-images.githubusercontent.com/35173068/104817869-25cdca80-584a-11eb-866c-77dc7bb04dab.png)

**Full Error Log** 

```
index.cjs.js:129 Uncaught FirebaseError: Function DocumentReference.update() called with invalid data. Unsupported field value: undefined (found in field name in document users/rlNDp5GQT1P4osAcT9GdNOI8ZUe2)
    at new t (https://eangadi-a2aa8.web.app/static/js/2.3b2c34a9.chunk.js:2:703108)
    at Ms (https://eangadi-a2aa8.web.app/static/js/2.3b2c34a9.chunk.js:2:904350)
    at e.c_ (https://eangadi-a2aa8.web.app/static/js/2.3b2c34a9.chunk.js:2:899127)
    at https://eangadi-a2aa8.web.app/static/js/2.3b2c34a9.chunk.js:2:902979
    at Is (https://eangadi-a2aa8.web.app/static/js/2.3b2c34a9.chunk.js:2:903016)
    at https://eangadi-a2aa8.web.app/static/js/2.3b2c34a9.chunk.js:2:900806
    at O (https://eangadi-a2aa8.web.app/static/js/2.3b2c34a9.chunk.js:2:704352)
    at ks (https://eangadi-a2aa8.web.app/static/js/2.3b2c34a9.chunk.js:2:900701)
    at t.update (https://eangadi-a2aa8.web.app/static/js/2.3b2c34a9.chunk.js:2:932378)
    at https://eangadi-a2aa8.web.app/static/js/main.3a8a858c.chunk.js:1:121205
t @ index.cjs.js:129
Ms @ index.cjs.js:13928
e.c_ @ index.cjs.js:13652
(anonymous) @ index.cjs.js:13855
Is @ index.cjs.js:13812
(anonymous) @ index.cjs.js:13720
O @ index.cjs.js:306
ks @ index.cjs.js:13715
t.update @ index.cjs.js:15285
(anonymous) @ authActions.js:93
(anonymous) @ index.js:8
updateUserInfo @ CartAddress.js:232
onSubmit @ CartAddress.js:140
s @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
at @ react-dom.production.min.js:52
it @ react-dom.production.min.js:51
st @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
M @ react-dom.production.min.js:287
B @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Qt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
D @ react-dom.production.min.js:287
Xt @ react-dom.production.min.js:68
```

**Comment by tbharathchandra** [comment]
Thank you @rtcms for reporting this issue

It is just a small change, we just fixed it.
